name: sast-sonar

on: 
  push: 
    branches: 
      - master
      #Ejemplo de lo que se puede utilizar
      #- develop      
      #- *
    pull_request:
        #Ejemplo de lo que se puede utilizar
        #types: [opened, synchronize, reopened]
        #Test
        branches: [master]
  
jobs: 
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
            projectBaseDir: .
            args: >
              -Dsonar.projectKey=${{ github.event.repository.name}}
              -Dsonar.projectName=${{ github.event.repository.name}}
              -Dsonar.source=.
              -Dsonar.sourceEncoding=UTF-8
      
      - name: SonarQube Quality Gate Check
        uses: sonarsource/sonarqube-quality-gate-action@master
        
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          #SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} #OPTIONAL
        